### ISSUE TITLE
Help with the example

### ISSUE THREAD

**Issue by alexellis** [cheshire137/gogoamazonwish#4]
Hi @cheshire137 

This is a cool project

When running the example in main.go, I got this error: `./main.go:24:7: _itemID declared but not used`

Then when I used my own wishlist URL, I got this result:

```
Found 0 item(s):
```

```golang
package main

import (
  "fmt"
  "log"

  "github.com/cheshire137/gogoamazonwish/pkg/amazon"
)

func main() {
  url := "https://www.amazon.co.uk/hz/wishlist/ls/3N6F3YMWH6J7Q"
  wishlist, err := amazon.NewWishlist(url)
  if err != nil {
    log.Fatalln(err)
  }

  items, err := wishlist.Items()
  if err != nil {
    log.Fatalln(err)
  }

  fmt.Printf("Found %d item(s):\n\n", len(items))
  number := 1
  for _itemID, item := range items {
    fmt.Printf("%d) %s %s\n\n", number, item, _itemID)
    number++
  }
}

```

What do you think?

**Comment by cheshire137** [comment]
Oh man, I wonder if this was a Go version difference. I first built this with version 1.13.4, and I'm guessing that's no longer the latest version.

**Comment by alexellis** [comment]
Just looked more like a typo. I'll close this as I didn't see it was 3 years ago that you last updated it
